const date = new Date()

console.log(date.toLocaleString('en-IN'))
console.log(date.getTime())
console.log(date.getMilliseconds())
console.log(date.getSeconds())
console.log(date.getMinutes())
console.log(date.getHours())
console.log(date.getDay())
console.log(date.getMonth())
console.log(date.getFullYear())
console.log(date.getTimezoneOffset()/60)